# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MyServer.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(688, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listenButton = QtWidgets.QPushButton(self.centralwidget)
        self.listenButton.setGeometry(QtCore.QRect(190, 100, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.listenButton.setFont(font)
        self.listenButton.setObjectName("listenButton")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 140, 671, 411))
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.image_label = QtWidgets.QLabel(self.groupBox)
        self.image_label.setGeometry(QtCore.QRect(170, 60, 331, 341))
        self.image_label.setFrameShape(QtWidgets.QFrame.Box)
        self.image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.image_label.setObjectName("image_label")
        self.ip_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.ip_edit.setGeometry(QtCore.QRect(60, 10, 191, 31))
        self.ip_edit.setObjectName("ip_edit")
        self.port_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.port_edit.setGeometry(QtCore.QRect(480, 10, 191, 31))
        self.port_edit.setObjectName("port_edit")
        self.bind_button = QtWidgets.QPushButton(self.centralwidget)
        self.bind_button.setGeometry(QtCore.QRect(190, 50, 321, 41))
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.bind_button.setFont(font)
        self.bind_button.setObjectName("bind_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(430, 20, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 688, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.listenButton.setText(_translate("MainWindow", "LISTEN"))
        self.groupBox.setTitle(_translate("MainWindow", "Patient\'s Data "))
        self.image_label.setText(_translate("MainWindow", "Image "))
        self.bind_button.setText(_translate("MainWindow", "BIND"))
        self.label.setText(_translate("MainWindow", "IP"))
        self.label_2.setText(_translate("MainWindow", "Port"))
